---
name              : zim-parser
version           : 0.2.0.0
stability         : alpha
category          : Codec
synopsis          : Read and parse ZIM files
description       : |
  zim-parser is a library to read and parse ZIM (http://openzim.org) files.
  ZiM files contain offline web content (eg. Wikipedia) which can be browsed
  locally without an Internet connection.

license           : GPL-3
author            : Robbin C. <robbinch33@gmail.com>
maintainer        : Robbin C. <robbinch33@gmail.com>
copyright         : Copyright (c) 2015 Robbin C.
github            : robbinch/zim-parser
ghc-options       : -Wall
extra-source-files: test/wikipedia_en_ray_charles_2015-06.zim

dependencies:
  - base == 4.*
  - base-compat
  - array
  - binary
  - bytestring
  - conduit
  - conduit-extra
  - binary-conduit
  - lzma

source-dirs: src

library:
  exposed-modules: Codec.Archive.Zim.Parser

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - hspec == 2.*
